### ISSUE TITLE
Rename feature (refactoring)

### ISSUE THREAD

**Issue by helperman** [Denis-net/vscode-ahk-manager#14]
Please add feature to rename all occurences of variables/functions/etc by F2.
It's crucial for everyone how works with code.
It makes code clear and better.

**Comment by Denis-net** [comment]
Good evening @helperman 😊👋🏻

My extension don't deal with syntax, it acts more like a bridge between VS Code and the AHK exe.
There are other AHK extensions for VSC that will help you to format code, syntax highlight, goto method definition etc..

I wrote this extension because I really needed it in VSC (previously i used Sublime).

VSC is great but the support for languages is generic and is splitted in more than one mechanism.
For example syntax coloring is performed following a particular RegEx in a JSON file and extension can't use it for other purposes.
For another project I have tried to integrate a parser that could tokenize the file and give me better context information (for example if the cursor is inside a comment) but without luck.
I'm not so good with syntax parsing: (because VSC exposes just the currently opened text to extension developer and this is just a bunch of characters, with no clue about context).

The context is very important because you can't just replace all similar text, because the var `foo` in the method `bar()` is different from the `foo` in the `fooBar()` method.

Having said so...

Have you tried to use `Ctrl+D` for selecting next occurrences of a selection ?
Other shortcuts very useful are `Ctrl+F` and `Ctrl+Shift+F`, the former allows you to find all occurrences, while the latter allow you to expand the researches across all files in the folder (both allow you to replace them, and you can also use regexes).
This is how I refactor currently.

**Comment by helperman** [comment]
Thanks for your explanation.
I think I will have to wait for an appropriate extension for my needs.
Ctrl + D is an interesting feature and will try it, thanks, but it is not so convenient after working with C# & Resharper in Visual Studio using Rename feature.

**Comment by Denis-net** [comment]
How can I blame you :
They cause so addiction 😜👍🏻
(I'm a fan too)
(In my opinion, the VSC multicursor is even more powerful than the VS one)

**Comment by helperman** [comment]
Wow! Multicursors is a really excellent feature! Will use it!

**Comment by Denis-net** [comment]
They are a real life saver !

There are many ways, my favorites are:
1) `Alt` click for adding/removing them wherever you want
2) Holding the `middle` mouse button and selecting a column (one cursor per line)
3) `Ctrl+D` 
4) `Shift+Alt+I` for splitting a whole selection into ending multicursor

Enjoy ! 😄✌🏻
