### ISSUE TITLE
Do not hide error info

### ISSUE THREAD

**Issue by helperman** [Denis-net/vscode-ahk-manager#15]
If you launch a script with any syntax error, for ex:
OutputDebugg Hello world
by feature "Run script", an error appears and the script doesn't run:
"An error has occurred while launching the executable: Error: Command failed: "c:\Program Files\AutoHotKey\AutoHotkey.exe" /ErrorStdOut /r "c:\AHK\Test1.ahk"

It might be quite puzzling to find an error in a big script without any additional information. 
How can I remove ErrorStdOut parameter or show more info about the line of code involved?
Pleze fix

**Comment by Denis-net** [comment]
Hi @helperman 😊👋🏻

I tried to reproduce your issue but this is what i got:
![immagine](https://user-images.githubusercontent.com/45769702/67151344-40bb3300-f2c5-11e9-8eb7-7c0ce264b4e3.png)

Have you expanded the notification ?
I'm not sure but maybe this is an issue regarding the AutoHotkey.exe path.
Please check the executable location and set the `ahk.executableFullPath` settings according.

Usually you can find it on `c:\Program Files\AutoHotKey\AutoHotkey.exe`, but during [AHK](https://www.autohotkey.com/) installation users can change its path.

**Comment by helperman** [comment]
OK, thanks, now I see it.
Maybe I didn't pay attention to this message or I tested using another example.
Maybe I was wrong about it.
Sorry.

**Comment by helperman** [comment]
Hi, Denis.
I encountered an issue when an error text is hidden.
An error appears for example if I call a nonexistent function.
But it's hard to find what's wrong with a script if it is big. 
So I run a script manually and an error appears with a line number involved.
Here is a screenshot: 
https://i.imgur.com/2CWFcOr.png

**Comment by Denis-net** [comment]
Hey Anthony
I tested your script, 
but this is what i see:
![immagine](https://user-images.githubusercontent.com/45769702/67619129-19e68a80-f7f8-11e9-8e6f-7d94f55868ed.png)

When i only get Command failed is because i didn't specify the right executable file (i.e. AutoHotkey path is wrong).
Otherwise it will always inform you what it don't like.

Please check another time the ahk. settings.

(I was answering the other issue, but i need to find the rigth words, so stay tuned)

**Comment by Denis-net** [comment]
But the filepath seems rigth...

Strange...

**Comment by Denis-net** [comment]
I have simulated your environment:
![immagine](https://user-images.githubusercontent.com/45769702/67619288-04726000-f7fa-11e9-9eb0-f48113e581f0.png)

It works too.
Please check if the file "c:\Program Files\AutoHotKey\Autohotkey.exe" exists.

In VSC console there isn't nothing wrong ?

**Comment by Denis-net** [comment]
If you replace it with a 
"MsgBox, hello"
does it works ?

**Comment by helperman** [comment]
Hello, Denis. 
Since you said you can't reproduce it I started to figure it out by myself in a clear virtual machine.
And finally, I've found why it happens.
I use this script to sign Authotkey.exe to overcome well-knows issues with AHK:
https://autohotkey.com/board/topic/70449-enable-interaction-with-administrative-programs/
After that, I have the issue I described above.
Briefly, this script changes Authohotkey.exe and after that all ahk-scripts might work with programs launched with admin rights (for example, taskmgr.exe).

**Comment by Denis-net** [comment]
Intresting,
Thank you for the research.
Can you still interact with AutoHotkey.exe from VSC after that, right ?
It states that "CreateProcess fails", in my extension i use the node.js [exec](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) command which should use the shell.
I redirect the StdOut but is it possible that it doesn't write at all ?

Have you tried with [AHK Studio](https://www.autohotkey.com/boards/viewtopic.php?t=300) ?
Or run VSC as administrator and see if it write something ?

**Comment by Denis-net** [comment]
I have setup my VM machine, but when i clicked on the download button i got an 404.
Do you have a copy of that script ?
So i will conduct experiments.

**Comment by helperman** [comment]
Hello, Denis.
The script is over there:
[EnableUIAccess.zip](https://github.com/Denis-net/vscode-ahk-manager/files/3803154/EnableUIAccess.zip)

I've been using it over the last 6 years.
Yes, I can interact with AutoHotkey.exe, all extensions work and scripts are launched in VS Code.
I didn't expect this script to change any AutoHotkey's behavior except interaction with administrative programs.
In the past, I always coded using Scite4Autohotkey and used my own hotkey to launch ahk-file and there was no any issues with it. I retreived a path to currently opened ahk-script in Scite and launched  "Run %ahkFile%"

I tried AHK Studio earlier and it looked very buggy for me, even during installation so I rejected using it. But I highly appreciated awesome IntelliSense (code completion) using it.
Today I tried it again and found it doesn't work with a signed AutoHotkey.exe out-of-the-box.
Looks like I have to look for another approach.

**Comment by Denis-net** [comment]
Hi @helperman ! 

Thanks for the script 👍🏻

I was thinking: if you right click the script and select "Run script" the script will warn you about the errors ?
Because if so, i could extract the /ErrorStdOut param (inside an `ahk.defaultArgs`) and make the script speak (As you rightly proposed from the begin).

I'll definitely try to fix the signed executable interaction issues, but in the meanwhile this could do the trick.

**Comment by Denis-net** [comment]
A new version is available and the `ahk.defaultArgs` setting is reachable.

When you'll have time, give it a try.👍🏻

**Comment by helperman** [comment]
It works like a charm!

**Comment by Denis-net** [comment]
I'm glad that it worked !

I have conducted some experiments, but the results were not good:
``` Typescript
    // const ls = child_process.spawn(command, { cwd: cfg.extensionPath, shell: true });
            // ls.stdout.on('data', (data) => {
            //     console.log(`stdout: ${data}`);
            //     r(true);
            // });

            // ls.stderr.on('data', (error) => {
            //     console.error(`stderr: ${error}`);
            //     if (quiet) {
            //         console.log('error: ' + error);
            //     }
            //     else
            //         vscode.window.showErrorMessage("An error has occured while launching the executable: " + error);
            //     c(error);
            // });

            // ls.on('close', (code) => {
            //     console.log(`child process exited with code ${code}`); //2 
            // });

            
            child_process.exec(command, { cwd: cfg.extensionPath }, function callback(error: any, stdout: any, stderr: any) {
                if (error) {
                    if (quiet) {
                        console.log('error: ' + error);
                    }
                    else
                        vscode.window.showErrorMessage("An error has occured while launching the executable: " + error);
                    c(error);
                }
                else
                    r(true);
            });
```

1) With `spawn()` without `shell:true`, commands were simply ignored by Ahk.
2) With `spawn()` with `shell:true`, commands get processed, but Ahk (executing a script that contains error) simply returned error code 2, without telling me why (neither `stderr` nor `stdout` were called).
3) With `exec` i got the best result, but you know what i got: exactly what you have seen earlier.
Actually I didn't hide error info, i reported correctly all what Ahk replied to me:
![immagine](https://user-images.githubusercontent.com/45769702/68535982-64fdb300-034b-11ea-9079-700c5dda305b.png)

I read in this closed [issue](https://github.com/nodejs/node-v0.x-archive/issues/6797) that Node don't provide support for this (ShellExecuteEx), because Windows can't mix UAC and not-UAC and have issues in redirecting stdout and stderr, which is the only thing we would like to receieve back.

The only valid solution i found is our buddy `ahk.defaultArgs` workaround.

Another option could be "sign" VSCode (perhaps installing a certificate or something similar to what the script done with the Ahk) in order to align the two, but i don't know how to do such a thing.
Just thrown an idea...

At the moment, I ended the options, 
but i'm open to new roads ! 😜

Good evening ! 😊👋🏻
