### ISSUE TITLE
Shortcuts don't work?

### ISSUE THREAD

**Issue by yaronelh** [Denis-net/vscode-ahk-manager#18]
I might be doing something wrong but the shortcuts mentioned in the description don't work  for example if you want to reach the docks that says

Using "Ctrl+A Ctrl+D" you can consult the docs

It doesn't matter if I click Ctrl-a or Ctrl-D it just does the Windows behavior
did you intend it to work in a certain way?

**Comment by Denis-net** [comment]
Hey @yaronelh ! 😊👋🏻

As Matt Bickett reported, using `Ctrl`+`A` `Ctrl`+`something`, affects the normal `Ctrl`+`A` usage (For which I added the `Ctrl`+`A` `Ctrl`+`A` workaround) and this is a basic text editor action that extensions should not override.
For these reasons i have disabled them by default.
If you want to use shortcuts you should copy this [json](https://github.com/Denis-net/vscode-ahk-manager#keyboard-shortcuts) and paste it into your keybindings.json (You can reach it by clicking the VSC gear, selecting "Keyboard Shortcuts (`Ctrl`+`K` `Ctrl`+`S`)" 
![immagine](https://user-images.githubusercontent.com/45769702/68963065-5ba29980-07d6-11ea-902b-d86a076662e2.png)
then at the top (where you usually found "Show preview" with Markdown files) select the "Open Keyboard Shortcuts (JSON)"
![immagine](https://user-images.githubusercontent.com/45769702/68962506-10d45200-07d5-11ea-97ef-0e24948affe9.png)
Paste there the JSON (you should precede the paste with a comma),
You should end up with something like this:
![immagine](https://user-images.githubusercontent.com/45769702/68962769-9e17a680-07d5-11ea-8600-7889ed6b5b87.png)
(I have collapsed some commands)

Recently, I have found better keybindings: using `Ctrl`+`L` `Ctrl`+`old_something` the double `Ctrl`+`A` workaround is no longer needed.
If you still want shortcut with `Ctrl`+`A` you can pick them from [here](https://github.com/Denis-net/vscode-ahk-manager/blob/master/issues/keybindings/ctrl%2Ba.json).

Regarding the docs: I added some useful settings if you want to consult the documentation
![immagine](https://user-images.githubusercontent.com/45769702/68962999-34e46300-07d6-11ea-8f29-db26ee9ecaa3.png)

* `online` uses firefox by default and search for a broader therms
* `chm` uses the help file which AHK ships with (you can find it in the main AHK folder)
* `html` (first it downloads my [browser](https://github.com/Denis-net/AutoHotkeyBrowser)), expand the AHK help file and allow users to specify another style sheet. (This feature was requested by `bugrobot`)

With `ahk.docs` command you can:
* select AHK commands and show them on the docs
* just open the main page and perform your searches 

Does it work for you ?

**Comment by yaronelh** [comment]
wow... that's a lot, maybe just mention it somewhere that the shortcuts don't work out-of-the-box you need to perform some actions. not bad or anything just more understandable if it's described.

Regarding the docs, I don't have a command called  `ahk.docs `
just these after installation
https://i.imgur.com/kE8hF2A.png

**Comment by Denis-net** [comment]
You are right: after some updates i moved that part in the changelog.md.
I didn't noticed it, 
I'll improve the Readme.md,
Thank you 👍🏻

Yes, it's the "AHK: Open Docs" command (`ahk.docs` is the underlying VSC command, you can find references in the keybindings.json, "AHK: Open Docs" is its userfriendly label).

This extension shows AHK related commands only when the active file is an ahk script.

In the image those commands perform different operations:
* "AHK: Open Docs" is the docs launcher
* "AHK: Clear offline docs cache" is useful in `html mode`, after AHK updates (otherwise you would have an outdated unzipped docs)
* "AHK: Paste Default Docs Style" with this command the default style of the help file is pasted, so users can modify it and override the default stylesheet of the decompressed html's help file version (specifying the `ahk.overrideOfflineDocsStylePath` setting).

> I had an idea: i could try to hide the last two commands when you are in other modes

* "AHK: Clear scripts Meta-data": this is the most dangerous command:
my extension works with ahk scripts and store Meta-data for you, see them as Cookies.
With Meta-data my extension can store your scripts' icon, default arguments, preferred compile locations and so on.
With scripts' Meta-data you can list your scripts in the "AutoHotkey Manager" Panel (the sidebar treelist) and interact with them (stop/start/open in VSC/reveal in the explorer).

If you just want to delete specific scripts meta data you can stop the running script(if is running), and in the "Script Memories" section of the "AutoHotkey Manager" panel you can "Forget" it
![immagine](https://user-images.githubusercontent.com/45769702/68996451-79393700-089a-11ea-801e-1c3d3ed413c9.png)

So, "AHK: Clear scripts Meta-data" can forget them all in batch, when you want to do so.
Is "dangerous" for my extension memories only, not for your scripts 😉, because no script is deleted, just my cfg file.😇
Yes after a forgot you'll have to set your script arguments (if any) again, but that's another story.

**Comment by yaronelh** [comment]
tried it, the play button on the memories panel doesn't work it gives an error of "file name, the directory name.... syntax is incorrect"

I think it might be the spaces issue just in a different location of the program

**Comment by Denis-net** [comment]
Have you moved the compiled executable ?
Or does the path contains spaces ?
If you hover the item what do you see ?
(It should display compiled destination with args)

**Comment by Denis-net** [comment]
We have found the bug: I wrapped with two pairs of double quotes the AHK executable (this happened only with ahk script, not with compiled exe).

Now should be fixed.
My VSC has just installed the v0.0.17 and fom my end now it works.

**Comment by yaronelh** [comment]
Had the chance to check it, in 17 works on my end as well
