### ISSUE TITLE
Get this error on VSCode startup

### ISSUE THREAD

**Issue by taoliu12** [Denis-net/vscode-ahk-manager#20]
[Denis-net.vscode-ahk-manager]: Unknown language in `contributes.vscode-ahk-manager.language`. Provided value: ahk

**Comment by Denis-net** [comment]
Hey @taoliu12 ! 😊👋🏼

I think you haven't installed any other ahk extensions yet.
This happens because my extension provides snippets, but VSC can't recognize the target language and given that no extension provides syntax higlights, no `ahk` label appears in your language selector.
See this:
![ahkIssue](https://user-images.githubusercontent.com/45769702/69912153-971fa380-1425-11ea-8191-c05b03cd304c.gif)

I guess you can't see it.
There are other ahk extensions, which will define the language selector in VSC:
![immagine](https://user-images.githubusercontent.com/45769702/69912192-00071b80-1426-11ea-89a4-66c9de203253.png)

(The sad truth about the other extensions is that they are fork of fork, in cascade [as you can see](https://github.com/stef-levesque/vscode-autohotkey/network/members).
They have added an unique functionality, keeping all the code of the others.
They should agree about the competence areas in order to provide a better ahk support to the users, so that they can install extensions separately or all together (as i would like to do) and report issues more accurately or at least having the chance to report them (try to open an issue in a forked project if you can... although [cweijan](https://github.com/cweijan/vscode-autohotkey) have forked the project the issue page is avaliable on its project: interesting).)

My extension don't deals with syntax, it's a bridge between two wonderful worlds: VSC and AHK.
I added snippets because this was initially a port of the awesome [Sublime Text AHK Plugin](https://github.com/ahkscript/SublimeAutoHotkey) then i added more features that could help you during the development.
At the time there was only the [stef-levesque's extension](https://marketplace.visualstudio.com/items?itemName=slevesque.vscode-autohotkey) available in VSC.

I decided to craft this extension because :
> _I like to write AutoHotkey scripts, this language is amazing, but I often found myself go back and forth between writing an app, looking for it in my messy tray, reloading it, testing it, grab the browser and tuning it again. So I decided to improve my tools and add the capabiliy to just reload a script through a command and/or a button._

Please try to install one of the other extensions and let me know if it does the trick.
(My extension is just a companion, and in VSC is great with syntax colors 😉)
