### ISSUE TITLE
I don't understand the possibilities of some `features`.

### ISSUE THREAD

**Issue by rediffusion** [Denis-net/vscode-ahk-manager#22]
I read all the instructions carefully, but there are still questions... 

For what are these commands? Tried to use but no effect. 🤐
Maybe you can show some screencast?

```
ahk.onSave.compile
ahk.onsave.run
ahk.set-script-arguments
```

**Comment by Denis-net** [comment]
Good day @rediffusion !😄👋🏼

I'll reply to you in reversed order, because it makes sense:

### `ahk.set-script-arguments`
![set-script-arguments](https://user-images.githubusercontent.com/45769702/71319864-0aa45600-24a4-11ea-9e57-bc435c117ed4.gif)
As you can see in the [second gif](https://raw.githubusercontent.com/Denis-net/vscode-ahk-manager/master/media/vs-ahk-manager-run-args.gif) on the main page, ahk scripts can work like cmd scripts, accepting arguments from the command line ([see this page](https://www.autohotkey.com/docs/Scripts.htm#cmd) for the topic).
AHK creates numbered variables for you that you can use in your code to refer to the parameters of your scripts.

My extension allow you to test the behaviour of your script with the passed arguments without leave VSC !😊
Otherwise you'll have to follow these steps: 
1. compile your script, 
2. open a prompt, 
3. cd to the parent dir, 
4. finally type 
``` bash
$> test.exe "кириллица"
```

(If you need an more advanced example about what can be done with parameters on a script take a look at [this script](https://github.com/Denis-net/SendToNewFolder/blob/master/SendToNewFolder.ahk) which i wrote long ago) 
___
### `ahk.onsave.run`
![onSave run](https://user-images.githubusercontent.com/45769702/71319995-936fc180-24a5-11ea-8f20-b626a50cebb2.gif)

When this option is set to `true`, after the first run, as soon as you save your script it will be re-launched for you without hitting the play button again.
It will also take the scripts arguments previously set into account.
Not a big feature, but sometimes could speed up the development process a bit.
___
### `ahk.onsave.compile`
![onSave compile](https://user-images.githubusercontent.com/45769702/71320082-dbdbaf00-24a6-11ea-99b5-ccad08f1a45f.gif)

Very similar to the `ahk.onSave.run` option: When set to `true`, after the first compile, it will compile for you the scripts as soon as you save them.

The reverse order is because each option don't exclude the others and in the code they are handled in this order 😉
___
Is it clearer now ?
Let me know if you have any further questions.
Have you some suggestions about how i could improve the main page in order to make it even more accessible to other users as well ?

**Comment by Denis-net** [comment]
Happy new year !!!🎉🎊
