### ISSUE TITLE
[BUG] command 'ahk.run' not found

### ISSUE THREAD

**Issue by BanditTech** [Denis-net/vscode-ahk-manager#8]
For Version 0.0.7:
When I click the Run Script play button it pops up an error: command 'ahk.run' not found
when I press the Kill Exe/Script it says: command 'ahk.kill' not found
same with lightning bolt: command 'ahk.run-buffer' not found

Problem goes away once I reinstall old version. (0.0.6)

**Comment by 08wckster08** [comment]
same issue here.

**Comment by Denis-net** [comment]
Hey @BanditTech and @08wckster08  !

Thank you for the feedback.
I tried to bundling The v0.0.7.
And in Debug mode on my machine it worked.

Something went wrong with the webpack.config:
I'm new to this thing, but I need it in order to continue the development.
I think the problem is about the node_modules folder integration.

You are rigth : for now is safer to use the v0.0.6

I need further investigations.
I'm terribly sorry for the inconvenience.

**Comment by Denis-net** [comment]
Ok, I have good news:
I found the issue with the .vscode-ignore: now we have the extension working again,
plus it's reduced in size ! 🎊🎉

I also fixed the extension path, because bundling an extension does change the 'relative' paths.

Please, give to the v0.0.9 a try.

If you found other issues let me know and I'll fix them 👍🏻
Thanks you again !
Thanks you also for having downloaded/used my extension.

**Comment by BanditTech** [comment]
Thank you for the attention to this, your work here is very appreciated.

**Comment by 08wckster08** [comment]
Thanks again for the fast response and the time dedicated to this ! Makes my life easier !
